api_version = "2024-10"
type = "theme"

[settings]
  [[settings.fields]]
    key = "weekly_discount"
    type = "number_integer"
    name = "Weekly Subscription Discount (%)"
    description = "Discount percentage for weekly subscriptions"
    default = 10

  [[settings.fields]]
    key = "biweekly_discount"
    type = "number_integer"
    name = "Bi-Weekly Subscription Discount (%)"
    description = "Discount percentage for every 2 weeks subscriptions"
    default = 5
