api_version = "2025-07"

[[extensions]]
name = "t:name"
handle = "hide-cod-subscriptions"
type = "function"
uid = "b96d89a2-9349-41d0-e766-c54dc889a53ea7d00088"
description = "t:description"

  [[extensions.targeting]]
  target = "cart.payment-methods.transform.run"
  input_query = "src/cart_payment_methods_transform_run.graphql"
  export = "cart-payment-methods-transform-run"

  [extensions.build]
  command = ""
  path = "dist/function.wasm"

  [extensions.ui.paths]
  create = "/"
  details = "/"
